generic-service:
  nameOverride: hmpps-dpr-fake-dps-service

  replicaCount: 2

  image:
    repository: quay.io/hmpps/hmpps-dpr-fake-dps-service
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: hmpps-dpr-fake-dps-service.hmpps.service.justice.gov.uk
    tlsSecretName: hmpps-dpr-fake-dps-service-cert

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-dpr-fake-dps-service:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
    api-token:
      API_TOKEN: "api_token"
    rds-postgresql-instance-output:
      SPRING_DATASOURCE_URL: "url"
      SPRING_DATASOURCE_USERNAME: "username"
      SPRING_DATASOURCE_PASSWORD: "password"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-dpr-fake-dps-service
  alertSeverity: digital-prison-reporting-dev
